/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.noor;

import java.awt.HeadlessException;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.lang.model.type.TypeKind.INT;
import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class AddNewEmployeeGUI extends javax.swing.JFrame {

    /**
     * Creates new form AddNewEmployeeGUI
     */
    public AddNewEmployeeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        salaryTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jobTitleTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        employeeIDTextField = new javax.swing.JTextField();
        depComboBox = new javax.swing.JComboBox<>();
        genderComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        depnComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Age");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Job");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Salary");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("department");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 183, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 254, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText("Phone");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 282, -1, -1));

        ageTextField.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 100, -1));

        salaryTextField.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(salaryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 100, -1));

        emailTextField.setBackground(new java.awt.Color(255, 255, 204));
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 100, -1));

        phoneTextField.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(phoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 100, -1));

        submitButton.setBackground(new java.awt.Color(0, 0, 0));
        submitButton.setForeground(new java.awt.Color(255, 255, 204));
        submitButton.setText("submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        jobTitleTextField.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(jobTitleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 100, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setText("ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        employeeIDTextField.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(employeeIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 100, -1));

        depComboBox.setBackground(new java.awt.Color(255, 255, 204));
        depComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Front Desk", "Housekeeping", "Kitchen", "Maintenance","IT" }));
        getContentPane().add(depComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 100, -1));

        genderComboBox.setBackground(new java.awt.Color(255, 255, 204));
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        getContentPane().add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 100, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel10.setText("dep_num");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 214, 62, -1));

        depnComboBox.setBackground(new java.awt.Color(255, 255, 204));
        depnComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4","5" }));
        getContentPane().add(depnComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 100, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dream4net\\OneDrive\\سطح المكتب\\emp.jpg")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 490, 350));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 204));
        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        nameTextField.setBackground(new java.awt.Color(255, 255, 204));
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 100, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dream4net\\OneDrive\\سطح المكتب\\Screenshot.png")); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(220, 400));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
       
        try {
            addEmployeeToDatabase();
        } catch (Exception ex) {
            Logger.getLogger(AddNewEmployeeGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_submitButtonActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();

   

    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

private void addEmployeeToDatabase() throws ClassNotFoundException {
    try {
       
          DriverManager.registerDriver(new org.postgresql.Driver ());
        Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/DB", "postgres", "123");
            
            if (isEmployeeIdExists((Connection) connection, Integer.parseInt(employeeIDTextField.getText()))) {
               JOptionPane.showMessageDialog(this, "Employee ID already exists", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            String insertEmployeeSql = "INSERT INTO employee (name, EmployeeID, age, gender, Job_title, Salary, dep_name, Email, Phone, Dep_no) " +
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            String updateDepartmentSql = "UPDATE department SET dep_employees = dep_employees + 1 WHERE dep_name = ?";
            try (PreparedStatement insertEmployeeStatement = connection.prepareStatement(insertEmployeeSql);
                    PreparedStatement updateDepartmentStatement = connection.prepareStatement(updateDepartmentSql)) {
                
                insertEmployeeStatement.setString(1, nameTextField.getText());
                insertEmployeeStatement.setInt(2, Integer.parseInt(employeeIDTextField.getText()));
                insertEmployeeStatement.setInt(3, Integer.parseInt(ageTextField.getText()));
                insertEmployeeStatement.setString(4, genderComboBox.getSelectedItem().toString());
                insertEmployeeStatement.setString(5, jobTitleTextField.getText());
                insertEmployeeStatement.setBigDecimal(6, new BigDecimal(salaryTextField.getText()));
                insertEmployeeStatement.setString(7, depComboBox.getSelectedItem().toString());
                insertEmployeeStatement.setString(8, emailTextField.getText());
                insertEmployeeStatement.setString(9, phoneTextField.getText());
                insertEmployeeStatement.setInt(10, Integer.parseInt((String) depnComboBox.getSelectedItem()));
                
                
                insertEmployeeStatement.executeUpdate();
                
                
                updateDepartmentStatement.setString(1, depComboBox.getSelectedItem().toString());
                updateDepartmentStatement.executeUpdate();
                
                
               JOptionPane.showMessageDialog(this, "Employee added successfully", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "noorr", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
}




private boolean isEmployeeIdExists(Connection connection, int employeeId) throws SQLException {
    String sql = "SELECT COUNT(*) FROM employee WHERE EmployeeID = ?";
    try (PreparedStatement statement = connection.prepareStatement(sql)) {
        statement.setInt(1, employeeId);
        try (ResultSet resultSet = statement.executeQuery()) {
            if (resultSet.next()) {
                int count = resultSet.getInt(1);
                return count > 0;
            }
        }
    }
    return false;
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddNewEmployeeGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextField;
    private javax.swing.JComboBox<String> depComboBox;
    private javax.swing.JComboBox<String> depnComboBox;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField employeeIDTextField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jobTitleTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField salaryTextField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
