/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.noor;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * 
 */
public class EmployeeGUI extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeGUI
     */
    public EmployeeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        addEmployeeButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addEmployeeButton.setBackground(new java.awt.Color(0, 0, 0));
        addEmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        addEmployeeButton.setText("Add new employee");
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 150, 20));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("edit employee info");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 150, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("remove an employee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 150, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Employees info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 130, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("salaries report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dream4net\\OneDrive\\سطح المكتب\\iStock_000012204568_Large.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButtonActionPerformed
  AddNewEmployeeGUI addNewEmployeeGUI = new AddNewEmployeeGUI();
    addNewEmployeeGUI.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_addEmployeeButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        updateEmployeeInfo();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        displayEmployeeInformation();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       deleteEmployee();
    }//GEN-LAST:event_jButton3ActionPerformed
private void deleteEmployee() {
    try {
        
        DriverManager.registerDriver(new org.postgresql.Driver ());
            Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/DB", "postgres", "123");
            String employeeIdInput = JOptionPane.showInputDialog(this, "Enter Employee ID to delete:", "Delete Employee", JOptionPane.QUESTION_MESSAGE);
            
            if (employeeIdInput != null && !employeeIdInput.isEmpty()) {
                int employeeId = Integer.parseInt(employeeIdInput);
                
                
                int departmentNumber = getDepartmentNumberForEmployee(connection, employeeId);
                
                
                deleteEmployee(connection, employeeId);
                
                
                decrementDepartmentEmployeesCount(connection, departmentNumber);
                
                
                JOptionPane.showMessageDialog(this, "Employee deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        }
     catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}


private void deleteEmployee(Connection connection, int employeeId) throws SQLException {
    String deleteSql = "DELETE FROM employee WHERE employeeid = ?";
    try (PreparedStatement deleteStatement = connection.prepareStatement(deleteSql)) {
        deleteStatement.setInt(1, employeeId);
        deleteStatement.executeUpdate();
    }
}


private int getDepartmentNumberForEmployee(Connection connection, int employeeId) throws SQLException {
    String sql = "SELECT dep_no FROM Employee WHERE EmployeeID = ?";
    try (PreparedStatement statement = connection.prepareStatement(sql)) {
        statement.setInt(1, employeeId);
        try (ResultSet resultSet = statement.executeQuery()) {
            if (resultSet.next()) {
                return resultSet.getInt("dep_no");
            }
            return -1;
        }
    }
}


private void decrementDepartmentEmployeesCount(Connection connection, int departmentNumber) throws SQLException {
    String updateSql = "UPDATE Department SET dep_employees = dep_employees - 1 WHERE Dep_num = ?";
    try (PreparedStatement updateStatement = connection.prepareStatement(updateSql)) {
        updateStatement.setInt(1, departmentNumber);
        updateStatement.executeUpdate();
    }
}

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 Connection con;
    InputStream input;
    JasperDesign jd;
    JasperReport jr;
    JasperPrint jp;
    OutputStream output;

    try {
        DriverManager.deregisterDriver(new org.postgresql.Driver());
        con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/DB", "postgres", "123");

        input = new FileInputStream(new File("salaries.jrxml"));
        jd = JRXmlLoader.load(input);
        jr = JasperCompileManager.compileReport(jd);
        jp = JasperFillManager.fillReport(jr, null, con);
      
        JFrame frame=new JFrame ("Report");
        frame.getContentPane () .add (new JRViewer (jp) ) ;
        frame. pack ();
        frame.setVisible (true);
        input.close();
        con.close();

      
        JOptionPane.showMessageDialog(null, "PDF report 'salaries report' created successfully!");

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.toString());
    }
    }//GEN-LAST:event_jButton5ActionPerformed
private void removeEmployeeFromDatabase(int employeeId, String departmentName) {
    try {
       
                   DriverManager.registerDriver(new org.postgresql.Driver ());
                Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/DB", "postgres", "123");

           
            String deleteEmployeeSql = "DELETE FROM employee WHERE EmployeeID = ?";
            String updateDepartmentSql = "UPDATE department SET dep_employees = dep_employees - 1 WHERE dep_name = ?";
            try (PreparedStatement deleteEmployeeStatement = connection.prepareStatement(deleteEmployeeSql);
                    PreparedStatement updateDepartmentStatement = connection.prepareStatement(updateDepartmentSql)) {
                
                
                deleteEmployeeStatement.setInt(1, employeeId);
                
                
                int rowsDeleted = deleteEmployeeStatement.executeUpdate();
                
                if (rowsDeleted > 0) {
                    
                    javax.swing.JOptionPane.showMessageDialog(this, "Employee removed successfully", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    
                    
                    updateDepartmentStatement.setString(1, departmentName);
                    int rowsUpdated = updateDepartmentStatement.executeUpdate();
                    
                    if (rowsUpdated <= 0) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Failed to update department", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to remove employee", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        
    } catch (SQLException ex) {
      
        ex.printStackTrace();
    }
}

    private void displayEmployeeInformation() {
    try {
         DriverManager.registerDriver(new org.postgresql.Driver ());
        Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/DB", "postgres", "123");
           
            String sql = "SELECT * FROM Employee";
            try (java.sql.PreparedStatement statement = connection.prepareStatement(sql)) {
                
                try (java.sql.ResultSet resultSet = statement.executeQuery()) {
                    
                    DefaultTableModel tableModel = new DefaultTableModel();
                    
                    
                    
                    tableModel.addColumn("name");
                    tableModel.addColumn("employeeid");
                    tableModel.addColumn("age");
                    tableModel.addColumn("gender");
                    tableModel.addColumn("Job Title");
                    tableModel.addColumn("Salary");
                    tableModel.addColumn("dep_name");
                    tableModel.addColumn("Email");
                    tableModel.addColumn("Phone");
                    tableModel.addColumn("dep_no");
                    
                    
                    
                    
                    while (resultSet.next()) {
                        Object[] rowData = {
                            
                            resultSet.getString("name"),
                            resultSet.getInt("employeeid"),
                            resultSet.getInt("age"),
                            resultSet.getString("gender"),
                            resultSet.getString("Job_title"),
                            resultSet.getDouble("Salary"),
                            resultSet.getString("dep_name"),
                            resultSet.getString("Email"),
                            resultSet.getString("Phone"),
                            resultSet.getInt("dep_no")
                                
                                
                        };
                        tableModel.addRow(rowData);
                    }
                    
                    
                    JTable employeeTable = new JTable(tableModel);
                    
                    
                    JOptionPane.showMessageDialog(this, new JScrollPane(employeeTable), "Employee Information", JOptionPane.PLAIN_MESSAGE);
                }
            }
        
    } catch (java.sql.SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}
   private void updateEmployeeInfo() {
    try {
              DriverManager.registerDriver(new org.postgresql.Driver ());
       Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/DB", "postgres", "123");
            
            String sql = "UPDATE Employee SET phone = ?, salary = ?, job_title = ?, email = ? WHERE EmployeeID = ?";
            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                
                String employeeIdInput = JOptionPane.showInputDialog(this, "Enter Employee ID:", "Update Employee Information", JOptionPane.QUESTION_MESSAGE);
                String newPhoneInput = JOptionPane.showInputDialog(this, "Enter New Phone:", "Update Employee Information", JOptionPane.QUESTION_MESSAGE);
                String newSalaryInput = JOptionPane.showInputDialog(this, "Enter New Salary:", "Update Employee Information", JOptionPane.QUESTION_MESSAGE);
                String newJobTitleInput = JOptionPane.showInputDialog(this, "Enter New Job Title:", "Update Employee Information", JOptionPane.QUESTION_MESSAGE);
                String newEmailInput = JOptionPane.showInputDialog(this, "Enter New Email:", "Update Employee Information", JOptionPane.QUESTION_MESSAGE);
                
                if (employeeIdInput != null && newPhoneInput != null &&
                        newSalaryInput != null && newJobTitleInput != null && newEmailInput != null &&
                        !employeeIdInput.isEmpty() && !newPhoneInput.isEmpty() &&
                        !newSalaryInput.isEmpty() && !newJobTitleInput.isEmpty() && !newEmailInput.isEmpty()) {
                    
                    int employeeId = Integer.parseInt(employeeIdInput);
                    
                    
                    statement.setString(1, newPhoneInput);
                    statement.setDouble(2, Double.parseDouble(newSalaryInput));
                    statement.setString(3, newJobTitleInput);
                    statement.setString(4, newEmailInput);
                    
                    statement.setInt(5, employeeId);
                    
                    
                    int rowsAffected = statement.executeUpdate();
                    
                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(this, "Employee information updated successfully!");
                    } else {
                        JOptionPane.showMessageDialog(this, "Employee not found or information update failed.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EmployeeGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

   private void performManageAction(String selectedOption) {
    // Perform action based on the selected option
    switch (selectedOption) {
        case "Add New Employee":
            // Add New Employee (to be implemented)
            JOptionPane.showMessageDialog(this, "Add New Employee selected.");
            break;
        case "Add Room":
            // Add Room (to be implemented)
            JOptionPane.showMessageDialog(this, "Add Room selected.");
            break;
        case "Add Driver":
            // Add Driver (to be implemented)
            JOptionPane.showMessageDialog(this, "Add Driver selected.");
            break;
        default:
            // No option selected
            break;
    }
}

}
