/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.noor;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 
 */
public class ReceptionGUI extends javax.swing.JFrame {

    /**
     * Creates new form ReceptionGUI
     */
    public ReceptionGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 102, 0));
        jButton1.setText("New Guest Form");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        jButton2.setBackground(new java.awt.Color(153, 102, 0));
        jButton2.setText("Rooms");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 150, -1));

        jButton3.setBackground(new java.awt.Color(153, 102, 0));
        jButton3.setText("Departments");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 150, -1));

        jButton5.setBackground(new java.awt.Color(153, 102, 0));
        jButton5.setText("Guests info");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 150, -1));

        jButton6.setBackground(new java.awt.Color(153, 102, 0));
        jButton6.setText("Check out");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, -1));

        jButton7.setBackground(new java.awt.Color(153, 102, 0));
        jButton7.setText("update room status");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 150, -1));

        jButton8.setBackground(new java.awt.Color(153, 102, 0));
        jButton8.setText("services");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 150, -1));

        jButton9.setBackground(new java.awt.Color(153, 102, 0));
        jButton9.setText("back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jButton10.setBackground(new java.awt.Color(153, 102, 0));
        jButton10.setText("service  update");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 150, -1));

        jButton11.setBackground(new java.awt.Color(153, 102, 0));
        jButton11.setText("sent service to a guest");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 150, -1));

        jButton12.setBackground(new java.awt.Color(153, 102, 0));
        jButton12.setText("add new room");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dream4net\\OneDrive\\سطح المكتب\\hotel-reception.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 510, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 displayRoomInformation();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        displayGuestInformation();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        displayDepartmentInformation();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddGuestGUI addGuestGUI = new AddGuestGUI();

       
        addGuestGUI.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    checkOutGuest();
    CheckOutGUI r=new CheckOutGUI();
    r.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed
 
private void checkOutGuest() {
    try {
            DriverManager.registerDriver(new org.postgresql.Driver ());
        Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/DB", "postgres", "123");

      
        String sql = "SELECT * FROM Guest";

        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            
            try (ResultSet resultSet = statement.executeQuery()) {
                
                DefaultTableModel tableModel = new DefaultTableModel();

             
                tableModel.addColumn("GuestID");
                tableModel.addColumn("Name");
                tableModel.addColumn("room_occupied");
                tableModel.addColumn("Check-in Date");
                tableModel.addColumn("Check-out Date");

                
                while (resultSet.next()) {
                    Vector<Object> rowData = new Vector<>();
                    rowData.add(resultSet.getInt("guestid"));
                    rowData.add(resultSet.getString("name"));
                    rowData.add(resultSet.getInt("room_occupied"));
                    rowData.add(resultSet.getString("check_in"));
                    rowData.add(resultSet.getString("check_out"));

                    tableModel.addRow(rowData);
                }

              
                JTable guestTable = new JTable(tableModel);

                
                int option = JOptionPane.showConfirmDialog(this, new JScrollPane(guestTable), "Select a guest to check out", JOptionPane.OK_CANCEL_OPTION);
                
                if (option == JOptionPane.OK_OPTION) {
                
                    int selectedRow = guestTable.getSelectedRow();
                    
                 
                    if (selectedRow != -1) {
                       
                        int selectedGuestID = (int) tableModel.getValueAt(selectedRow, 0);
                        
                        
                        String updateSql = "UPDATE Guest SET check_out = ? WHERE GuestID = ?";
                        
                        try (PreparedStatement updateStatement = connection.prepareStatement(updateSql)) {
                           
                            updateStatement.setDate(1, new java.sql.Date(System.currentTimeMillis()));
                            updateStatement.setInt(2, selectedGuestID);
                            
                        
                            updateStatement.executeUpdate();
                        }
                        
                        
                        JOptionPane.showMessageDialog(this, "Guest checked out successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
        }

      
        connection.close();
    } catch (SQLException ex) {
      //  JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
       // ex.printStackTrace();
   }
}
                
       
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

updateRoomStatus();
    }//GEN-LAST:event_jButton7ActionPerformed
private void updateRoomStatus() {
    try {
              DriverManager.registerDriver(new org.postgresql.Driver ());
        Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/DB", "postgres", "123");

        
        String sql = "UPDATE Room SET avalbility = ?, cleaning_status = ?, price = ? WHERE RoomNum = ?";

        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            
            String roomNumInput = JOptionPane.showInputDialog(this, "Enter Room Number:", "Update Room Status", JOptionPane.QUESTION_MESSAGE);
            String newStatusInput = JOptionPane.showInputDialog(this, "Enter New Status (Vacant or Occupied):", "Update Room Status", JOptionPane.QUESTION_MESSAGE);
            String newCleaningStatusInput = JOptionPane.showInputDialog(this, "Enter New Cleaning Status:", "Update Room Status", JOptionPane.QUESTION_MESSAGE);
            String newPriceInput = JOptionPane.showInputDialog(this, "Enter New Price:", "Update Room Status", JOptionPane.QUESTION_MESSAGE);

            if (roomNumInput != null && newStatusInput != null && newCleaningStatusInput != null && newPriceInput != null &&
                !roomNumInput.isEmpty() && !newStatusInput.isEmpty() && !newCleaningStatusInput.isEmpty() && !newPriceInput.isEmpty()) {
                int roomNum = Integer.parseInt(roomNumInput);
                String newStatus = newStatusInput.trim().toLowerCase();
                String newCleaningStatus = newCleaningStatusInput.trim();
                double newPrice = Double.parseDouble(newPriceInput);

                
                statement.setString(1, newStatus);
                statement.setString(2, newCleaningStatus);
                statement.setDouble(3, newPrice);
                statement.setInt(4, roomNum);

             
                int rowsAffected = statement.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Room information updated successfully!");
                } else {
                    JOptionPane.showMessageDialog(this, "Room not found or information update failed.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

        
        connection.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}

    private void updateEventStatus() {
    try {
            DriverManager.registerDriver(new org.postgresql.Driver ());
        Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/DB", "postgres", "123");

       
        String sql = "UPDATE events SET EventStatus = ? WHERE EventID = ?";

        try (PreparedStatement statement = connection.prepareStatement(sql)) {
           
            String eventIDInput = JOptionPane.showInputDialog(this, "Enter Event ID:", "Update Event Status", JOptionPane.QUESTION_MESSAGE);
            String newStatusInput = JOptionPane.showInputDialog(this, "Enter New Event Status:", "Update Event Status", JOptionPane.QUESTION_MESSAGE);

            if (eventIDInput != null && newStatusInput != null && !eventIDInput.isEmpty() && !newStatusInput.isEmpty()) {
                int eventID = Integer.parseInt(eventIDInput);
                String newStatus = newStatusInput.trim();

               
                statement.setString(1, newStatus);
                statement.setInt(2, eventID);

                
                int rowsAffected = statement.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Event status updated successfully!");
                } else {
                    JOptionPane.showMessageDialog(this, "Event not found or status update failed.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

       
        connection.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          displayServicesInformation();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         this.dispose();

  
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      updateServiceStatus();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
       buyGUI r= new buyGUI();
      
    r.setVisible(true);
       
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        AddRoomGUI addRoomGUI = new AddRoomGUI();
    addRoomGUI.setVisible(true);  
    }//GEN-LAST:event_jButton12ActionPerformed



    private void updateServiceStatus() {
    try {
             DriverManager.registerDriver(new org.postgresql.Driver ());
        Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/DB", "postgres", "123");

        
        String sql = "UPDATE Services SET Availability = ?, Price = ? WHERE ServiceID = ?";

        try (PreparedStatement statement = connection.prepareStatement(sql)) {
           
            String serviceIdInput = JOptionPane.showInputDialog(this, "Enter Service ID:", "Update Service Status and Price", JOptionPane.QUESTION_MESSAGE);
            String newAvailabilityInput = JOptionPane.showInputDialog(this, "Enter New Availability (Available or Unavailable or comming soon):", "Update Service Status and Price", JOptionPane.QUESTION_MESSAGE);
            String newPriceInput = JOptionPane.showInputDialog(this, "Enter New Price:", "Update Service Status and Price", JOptionPane.QUESTION_MESSAGE);

            if (serviceIdInput != null && newAvailabilityInput != null && newPriceInput != null &&
                !serviceIdInput.isEmpty() && !newAvailabilityInput.isEmpty() && !newPriceInput.isEmpty()) {
                int serviceId = Integer.parseInt(serviceIdInput);
                String newAvailability = newAvailabilityInput.trim().toLowerCase();
                double newPrice = Double.parseDouble(newPriceInput);

                
                statement.setString(1, newAvailability);
                statement.setDouble(2, newPrice);
                statement.setInt(3, serviceId);

                
                int rowsAffected = statement.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Service status and price updated successfully!");
                } else {
                    JOptionPane.showMessageDialog(this, "Service not found or status/price update failed.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

        
        connection.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}


    private void displayServicesInformation() {
    try {
             DriverManager.registerDriver(new org.postgresql.Driver ());
        Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/DB", "postgres", "123");

       
        String sql = "SELECT * FROM Services";

        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(sql)) {

            
            DefaultTableModel tableModel = new DefaultTableModel();

          
            tableModel.addColumn("ServiceID");
            tableModel.addColumn("Service Name");
            tableModel.addColumn("Description");
            tableModel.addColumn("Price");
            tableModel.addColumn("Availability");

           
            while (resultSet.next()) {
                Vector<Object> rowData = new Vector<>();
                rowData.add(resultSet.getInt("ServiceID"));
                rowData.add(resultSet.getString("Service_name"));
                rowData.add(resultSet.getString("Description"));
                rowData.add(resultSet.getDouble("Price"));
                rowData.add(resultSet.getString("Availability"));

                tableModel.addRow(rowData);
            }

            
            JTable servicesTable = new JTable(tableModel);

            
            JOptionPane.showMessageDialog(this, new JScrollPane(servicesTable), "Services Information", JOptionPane.PLAIN_MESSAGE);
        }

      
        connection.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}
    private void displayRoomInformation() {
    try {
         DriverManager.registerDriver(new org.postgresql.Driver ());
 Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/DB", "postgres", "123");
       
        String sql = "SELECT * FROM Room";

        try (java.sql.PreparedStatement statement = connection.prepareStatement(sql)) {
           
            try (java.sql.ResultSet resultSet = statement.executeQuery()) {
               
                DefaultTableModel tableModel = new DefaultTableModel();

                
                tableModel.addColumn("Room Number");
                tableModel.addColumn("Price");
                tableModel.addColumn("Availability");
                tableModel.addColumn("Bed Type");
                tableModel.addColumn("Cleaning Status");

                
                while (resultSet.next()) {
                    Object[] rowData = {
                            resultSet.getInt("RoomNum"),
                            resultSet.getInt("Price"),
                            resultSet.getString("Avalbility"),
                            resultSet.getString("Bed_tybe"),
                            resultSet.getString("cleaning_status")
                    };
                    tableModel.addRow(rowData);
                }

                
                JTable roomTable = new JTable(tableModel);

               
                JOptionPane.showMessageDialog(this, new JScrollPane(roomTable), "Room Information", JOptionPane.PLAIN_MESSAGE);
            }
        }

        
        connection.close();
    } catch (java.sql.SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}
private void displayGuestInformation() {
    try {
         DriverManager.registerDriver(new org.postgresql.Driver ());
         Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/DB", "postgres", "123");

        
        String sql = "SELECT * FROM Guest";

        try (java.sql.PreparedStatement statement = connection.prepareStatement(sql)) {
           
            try (java.sql.ResultSet resultSet = statement.executeQuery()) {
                
                DefaultTableModel tableModel = new DefaultTableModel();

                
                tableModel.addColumn("GuestID");
                tableModel.addColumn("Name");
                tableModel.addColumn("Gender");
                tableModel.addColumn("Nationality");
                tableModel.addColumn("Room Occupied");
                tableModel.addColumn("Deposit");
                tableModel.addColumn("Phone");
                tableModel.addColumn("check_in");

               
                while (resultSet.next()) {
                    Object[] rowData = {
                            resultSet.getInt("GuestID"),
                            resultSet.getString("name"),
                            resultSet.getString("gender"),
                            resultSet.getString("Nationality"),
                            resultSet.getInt("room_occupied"),
                            resultSet.getInt("deposit"),
                            resultSet.getString("Phone"),
                            resultSet.getString("check_in")
                    };
                    tableModel.addRow(rowData);
                }

                
                JTable guestTable = new JTable(tableModel);

              
                JOptionPane.showMessageDialog(this, new JScrollPane(guestTable), "Guest Information", JOptionPane.PLAIN_MESSAGE);
            }
        }

    
        connection.close();
    } catch (java.sql.SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}

private void displayDepartmentInformation() {
    try {
         DriverManager.registerDriver(new org.postgresql.Driver ());
 Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/DB", "postgres", "123");
        
        String sql = "SELECT * FROM department";

        try (PreparedStatement statement = connection.prepareStatement(sql)) {
         
            try (ResultSet resultSet = statement.executeQuery()) {
               
                DefaultTableModel tableModel = new DefaultTableModel();

              
                tableModel.addColumn("Department Number");
                tableModel.addColumn("Department Name");
                tableModel.addColumn("Department Floor");
                tableModel.addColumn("Number of Employees");

                
                while (resultSet.next()) {
                    Object[] rowData = {
                            resultSet.getInt("dep_num"),
                            resultSet.getString("dep_name"),
                            resultSet.getInt("dep_floor"),
                            resultSet.getInt("dep_employees")
                    };
                    tableModel.addRow(rowData);
                }

               
                JTable departmentTable = new JTable(tableModel);

               
                JOptionPane.showMessageDialog(this, new JScrollPane(departmentTable), "Department Information", JOptionPane.PLAIN_MESSAGE);
            }
        }

     
        connection.close();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
